import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import NavigationHeader from "@/components/header";
import localFont from "next/font/local";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-roboto",
});

const yekanFont = localFont({
  src: "./fonts/yekan-regular.ttf",
  variable: "--font-yekan",
  weight: "500",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={yekanFont.className}>
        <NavigationHeader />
        {children}
      </body>
    </html>
  );
}
